version: '3.7'

services:
  client:
    container_name: popup-foodies_client
    image: popup-foodies-client:latest
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /client/node_modules
      - ./client:/popup-foodies
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    container_name: popup-foodies_server
    image: popup-foodies-server:latest
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /server/node_modules
      - ./server:/popup-foodies
  database:
    container_name: mongo_db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db

volumes:
  client:
  mongo_db:
  server:
